-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 13:00:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `memberID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `phoneNum1` CHAR(11) NOT NULL,
  `phoneNum2` CHAR(11) NULL,
  `phoneNum3` CHAR(11) NULL,
  `dob` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `radioNumber` VARCHAR(45) NOT NULL,
  `stationNumber` INT(11) NOT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`memberID`),
  UNIQUE INDEX `memberID_UNIQUE` (`memberID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certification` (
  `certificationID` INT NOT NULL AUTO_INCREMENT,
  `certName` VARCHAR(45) NOT NULL,
  `certAgency` VARCHAR(45) NOT NULL,
  `expDate` YEAR(4) NULL,
  `renewDate` YEAR(4) NULL,
  `expPeriod` VARCHAR(45) NULL,
  PRIMARY KEY (`certificationID`),
  UNIQUE INDEX `certificationID_UNIQUE` (`certificationID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`memberCertification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`memberCertification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`memberCertification` (
  `Certification_certificationID` INT NOT NULL,
  `Member_memberID` INT NOT NULL,
  PRIMARY KEY (`Certification_certificationID`, `Member_memberID`),
  INDEX `fk_Certification_has_Member_Member1_idx` (`Member_memberID` ASC) VISIBLE,
  INDEX `fk_Certification_has_Member_Certification_idx` (`Certification_certificationID` ASC) VISIBLE,
  CONSTRAINT `fk_Certification_has_Member_Certification`
    FOREIGN KEY (`Certification_certificationID`)
    REFERENCES `mydb`.`Certification` (`certificationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certification_has_Member_Member1`
    FOREIGN KEY (`Member_memberID`)
    REFERENCES `mydb`.`Member` (`memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Member (firstName, lastName, street, city, state, zip, phoneNum1, phoneNum2, dob, gender, startDate, position, radioNumber, stationNumber, isActive)
VALUES ('Kathryn', 'Pryde', '1123 Xavier School Drive', 'Watkinsville', 'GA', '30677', '17075551234', '7075552345', '1980-12-07', 'Female', '2014-05-27', 'Chief', 'A-1', 5, 1);

INSERT INTO Member (firstName, lastName, street, city, state, zip, phoneNum1, dob, gender, startDate, position, radioNumber, stationNumber, isActive)
VALUES ('Piotr', 'Rasputin', 'A31 Mother Russia Road', 'Seattle', 'WA', '98133', '2065559876', '1993-01-14', 'Male', '2018-07-29', 'Captain', '841', 8, 1);

INSERT INTO Member (firstName, lastName, street, city, state, zip, phoneNum1, dob, gender, startDate, position, radioNumber, stationNumber, isActive)
VALUES ('Warren', 'Worthington III', '1140 Experiment Station Rd', 'Watkinsville', 'GA', '30677', '7065553945', '1997-02-28', 'Male', '2020-05-17', 'Associate Firefighter', '122', 1, 1);
